export type OpportunityCategory =
  | "internships"
  | "scholarships"
  | "fellowships"
  | "competitions"
  | "hackathons"
  | "conferences"
  | "exchangePrograms"
  | "summerSchools"
  | "bootcamps"
  | "volunteering"
  | "studentJobs";

export type Opportunity = {
  id: number;
  title: string;
  organization: string;
  type: string;
  eligibility: string;
  country: string;
  remote: string;
  funding: string;
  link: string;
  category: OpportunityCategory;
  /**
   * ISO date string ("2026-11-30") when a hard deadline is known, or
   * omitted/undefined for rolling & not-yet-confirmed deadlines. The
   * source sheet doesn't include deadlines yet -- add them here as
   * they become available; the search/filter UI already supports it.
   */
  deadline?: string;
};

/**
 * Sourced from exel sheet and grouped into the
 * eleven sidebar categories. A handful of categories in the sheet
 * (Summer Schools, Student Jobs) have no rows yet -- those pages
 * will render their empty state until more data is added here.
 */
export const OPPORTUNITIES: Opportunity[] = [
  {
    id: 0,
    title: "Google Summer of Code",
    organization: "Google",
    type: "Open Source Internship",
    eligibility: "University Students",
    country: "Global",
    remote: "Yes",
    funding: "Paid",
    link: "https://summerofcode.withgoogle.com/",
    category: "internships",
  },
  {
    id: 1,
    title: "NASA Space Apps Challenge",
    organization: "NASA",
    type: "Hackathon",
    eligibility: "Everyone",
    country: "Global",
    remote: "Yes",
    funding: "Free",
    link: "https://www.spaceappschallenge.org/",
    category: "hackathons",
  },
  {
    id: 2,
    title: "Microsoft Imagine Cup",
    organization: "Microsoft",
    type: "Competition",
    eligibility: "Students",
    country: "Global",
    remote: "Hybrid",
    funding: "Prize",
    link: "https://imaginecup.microsoft.com/en-us",
    category: "competitions",
  },
  {
    id: 3,
    title: "GitHub Campus Experts",
    organization: "GitHub",
    type: "Student Program",
    eligibility: "University Students",
    country: "Global",
    remote: "Yes",
    funding: "Free",
    link: "https://github.com/education/students/campus-expert",
    category: "volunteering",
  },
  {
    id: 4,
    title: "MLH Fellowship",
    organization: "Major League Hacking",
    type: "Fellowship",
    eligibility: "Students",
    country: "Global",
    remote: "Yes",
    funding: "Paid",
    link: "https://fellowship.mlh.com/",
    category: "fellowships",
  },
  {
    id: 5,
    title: "Microsoft Learn Student Ambassadors",
    organization: "Microsoft",
    type: "Ambassador Program",
    eligibility: "Students",
    country: "Global",
    remote: "Yes",
    funding: "Free",
    link: "https://mvp.microsoft.com/studentambassadors",
    category: "volunteering",
  },
  {
    id: 6,
    title: "Google Developer Student Clubs",
    organization: "Google",
    type: "Student Community",
    eligibility: "University Students",
    country: "Global",
    remote: "Hybrid",
    funding: "Free",
    link: "https://gdg.community.dev/",
    category: "volunteering",
  },
  {
    id: 7,
    title: "HPAIR Conference",
    organization: "Harvard Project for Asian and International Relations",
    type: "Conference",
    eligibility: "Students",
    country: "Various",
    remote: "Hybrid",
    funding: "Partial Funding",
    link: "https://www.hpair.org/",
    category: "conferences",
  },
  {
    id: 8,
    title: "One Young World Scholarship",
    organization: "One Young World",
    type: "Scholarship",
    eligibility: "Young Leaders",
    country: "Global",
    remote: "No",
    funding: "Fully Funded",
    link: "https://www.oneyoungworld.com/scholarships",
    category: "scholarships",
  },
  {
    id: 9,
    title: "Deloitte One Young World Scholarship",
    organization: "Deloitte",
    type: "Scholarship",
    eligibility: "Students & Young Professionals",
    country: "Global",
    remote: "No",
    funding: "Fully Funded",
    link: "https://www.oneyoungworld.com/scholarships",
    category: "scholarships",
  },
  {
    id: 10,
    title: "UN Youth Delegate Programs",
    organization: "United Nations Partners",
    type: "Conference",
    eligibility: "Youth",
    country: "Various",
    remote: "No",
    funding: "Varies",
    link: "https://social.desa.un.org/issues/youth/un-youth-delegate-programme",
    category: "conferences",
  },
  {
    id: 11,
    title: "Aspire Leaders Program",
    organization: "Aspire Institute",
    type: "Leadership Program",
    eligibility: "University Students",
    country: "Global",
    remote: "Yes",
    funding: "Free",
    link: "https://engage.aspireleaders.org/",
    category: "fellowships",
  },
  {
    id: 12,
    title: "MITACS Globalink Research Internship",
    organization: "MITACS",
    type: "Research Internship",
    eligibility: "Undergraduate Students",
    country: "Canada",
    remote: "No",
    funding: "Fully Funded",
    link: "https://www.mitacs.ca/our-programs/globalink-research-internship-students/",
    category: "internships",
  },
  {
    id: 13,
    title: "CERN Openlab Summer Student Programme",
    organization: "CERN",
    type: "Research Internship",
    eligibility: "STEM Students",
    country: "Switzerland",
    remote: "No",
    funding: "Fully Funded",
    link: "https://openlab.cern/cern-openlab-summer-student-programme/",
    category: "internships",
  },
  {
    id: 14,
    title: "CERN Technical Student Programme",
    organization: "CERN",
    type: "Internship",
    eligibility: "STEM Students",
    country: "Switzerland",
    remote: "No",
    funding: "Paid",
    link: "https://careers.cern/programmes/technical-studentship/",
    category: "internships",
  },
  {
    id: 15,
    title: "Erasmus Mundus Scholarships",
    organization: "European Union",
    type: "Scholarship",
    eligibility: "Graduates",
    country: "Europe",
    remote: "No",
    funding: "Fully Funded",
    link: "https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters",
    category: "scholarships",
  },
  {
    id: 16,
    title: "DAAD EPOS Scholarships",
    organization: "DAAD",
    type: "Scholarship",
    eligibility: "Graduates",
    country: "Germany",
    remote: "No",
    funding: "Fully Funded",
    link: "https://www.daad.de/en/information-services-for-higher-education-institutions/further-information-on-daad-programmes/epos/",
    category: "scholarships",
  },
  {
    id: 17,
    title: "Schwarzman Scholars",
    organization: "Schwarzman Scholars",
    type: "Scholarship",
    eligibility: "Graduates",
    country: "China",
    remote: "No",
    funding: "Fully Funded",
    link: "https://www.schwarzmanscholars.org/admissions/",
    category: "scholarships",
  },
  {
    id: 18,
    title: "Chevening Scholarships",
    organization: "UK Government",
    type: "Scholarship",
    eligibility: "Graduates",
    country: "UK",
    remote: "No",
    funding: "Fully Funded",
    link: "https://www.rvc.ac.uk/study/scholarships-and-bursaries/other-funders/chevening?gad_source=1&gad_campaignid=23020487924&gbraid=0AAAAADitEfp1CxzrmfzREVTOjs0h0WDHL&gclid=CjwKCAjw1bvTBhBbEiwAzbP8LxOFrp5NABsGsxUVZ_K91PVxcmssv8kG-fhGcXo0x49KW7OIBPbjqRoCFocQAvD_BwE",
    category: "scholarships",
  },
  {
    id: 19,
    title: "Fulbright Foreign Student Program",
    organization: "U.S. Government",
    type: "Scholarship",
    eligibility: "Graduates",
    country: "USA",
    remote: "No",
    funding: "Fully Funded",
    link: "https://foreign.fulbrightonline.org/about/foreign-student-program",
    category: "scholarships",
  },
  {
    id: 20,
    title: "Commonwealth Scholarships",
    organization: "Commonwealth",
    type: "Scholarship",
    eligibility: "Graduates",
    country: "UK",
    remote: "No",
    funding: "Fully Funded",
    link: "https://cscuk.fcdo.gov.uk/about-us/scholarships/",
    category: "scholarships",
  },
  {
    id: 21,
    title: "Rhodes Scholarship",
    organization: "Rhodes Trust",
    type: "Scholarship",
    eligibility: "Graduates",
    country: "UK",
    remote: "No",
    funding: "Fully Funded",
    link: "https://www.rhodeshouse.ox.ac.uk/scholarships/the-rhodes-scholarship/",
    category: "scholarships",
  },
  {
    id: 22,
    title: "Knight-Hennessy Scholars",
    organization: "Stanford University",
    type: "Scholarship",
    eligibility: "Graduates",
    country: "USA",
    remote: "No",
    funding: "Fully Funded",
    link: "https://knight-hennessy.stanford.edu/admission/before-you-apply/eligibility",
    category: "scholarships",
  },
  {
    id: 23,
    title: "McCall MacBain Scholarships",
    organization: "McGill University",
    type: "Scholarship",
    eligibility: "Graduates",
    country: "Canada",
    remote: "No",
    funding: "Fully Funded",
    link: "https://mccallmacbainscholars.org/apply/",
    category: "scholarships",
  },
  {
    id: 24,
    title: "Youth4South Fellowship",
    organization: "Youth4South",
    type: "Fellowship",
    eligibility: "Youth",
    country: "Global",
    remote: "Hybrid",
    funding: "Funded",
    link: "https://unsouthsouth.org/2019/12/04/call-for-application-youth4south-fellowship-programme-2019/",
    category: "fellowships",
  },
  {
    id: 25,
    title: "UNESCO Youth Programs",
    organization: "UNESCO",
    type: "Fellowship",
    eligibility: "Youth",
    country: "Global",
    remote: "Hybrid",
    funding: "Varies",
    link: "https://www.unesco.org/en/youth",
    category: "fellowships",
  },
  {
    id: 26,
    title: "AFS Global STEM Academies",
    organization: "AFS Intercultural Programs",
    type: "Exchange",
    eligibility: "Students",
    country: "Global",
    remote: "Hybrid",
    funding: "Fully Funded",
    link: "https://afs.org/global-stem/academies/",
    category: "exchangePrograms",
  },
  {
    id: 27,
    title: "YSEALI Academic Fellows",
    organization: "U.S. Department of State",
    type: "Fellowship",
    eligibility: "Southeast Asia",
    country: "No",
    remote: "Fully Funded",
    funding: "",
    link: "https://www.ysealiafp.org/",
    category: "fellowships",
  },
  {
    id: 28,
    title: "Kectil Youth Leadership Program",
    organization: "Kectil",
    type: "Leadership",
    eligibility: "Youth",
    country: "Online",
    remote: "Yes",
    funding: "Free",
    link: "https://kectil.com/",
    category: "fellowships",
  },
  {
    id: 29,
    title: "International Astronomy and Astrophysics Competition",
    organization: "IAAC",
    type: "Competition",
    eligibility: "Students",
    country: "Global",
    remote: "Yes",
    funding: "Free",
    link: "https://iaac.space/en/",
    category: "competitions",
  },
  {
    id: 30,
    title: "Huawei ICT Competition",
    organization: "Huawei",
    type: "Competition",
    eligibility: "University Students",
    country: "Global",
    remote: "Hybrid",
    funding: "Prize",
    link: "https://www.huawei.com/minisite/ict-competition-2025-2026-global/en/index.html",
    category: "competitions",
  },
  {
    id: 31,
    title: "ICPC",
    organization: "ICPC Foundation",
    type: "Programming Competition",
    eligibility: "University Students",
    country: "Global",
    remote: "No",
    funding: "Prize",
    link: "https://icpc.global/",
    category: "competitions",
  },
  {
    id: 32,
    title: "World Bank Group Internship Program",
    organization: "World Bank Group",
    type: "Internship",
    eligibility: "Master's & PhD Students (Economics, Public Policy, Social Sciences)",
    country: "USA / Global",
    remote: "No",
    funding: "Paid",
    link: "https://www.worldbank.org/en/about/careers/programs-and-internships/internship",
    category: "internships",
  },
  {
    id: 33,
    title: "WHO Internship Programme",
    organization: "World Health Organization",
    type: "Internship",
    eligibility: "Health, Public Policy, Nursing & Social Sciences Students",
    country: "Global",
    remote: "Hybrid",
    funding: "Stipend Provided",
    link: "https://www.who.int/careers/internships",
    category: "internships",
  },
  {
    id: 34,
    title: "OECD Young Associates Programme",
    organization: "OECD",
    type: "Fellowship",
    eligibility: "Recent Undergraduates (Economics, Public Policy, Political Science)",
    country: "France",
    remote: "No",
    funding: "Paid",
    link: "https://www.oecd.org/careers/young-associates-programme/",
    category: "fellowships",
  },
  {
    id: 35,
    title: "Humanity in Action Fellowship",
    organization: "Humanity in Action",
    type: "Fellowship Program",
    eligibility: "Undergraduates & Recent Grads (Humanities, Social Sciences, Human Rights)",
    country: "USA / Europe",
    remote: "Hybrid",
    funding: "Fully Funded",
    link: "https://humanityinaction.org/fellowships/",
    category: "fellowships",
  },
  {
    id: 36,
    title: "L'Or\u00e9al Brandstorm Competition",
    organization: "L'Or\u00e9al",
    type: "Innovation Competition",
    eligibility: "Undergraduate & Graduate Students (All Fields / Business / Tech)",
    country: "Global",
    remote: "Yes",
    funding: "Prize / Mentorship",
    link: "https://brandstorm.loreal.com/",
    category: "competitions",
  },
  {
    id: 37,
    title: "Sony World Photography Awards (Student)",
    organization: "World Photography Organisation",
    type: "Arts & Design Competition",
    eligibility: "Students studying Photography, Fine Arts & Visual Media",
    country: "Global",
    remote: "Yes",
    funding: "Equipment & Travel Grant",
    link: "https://www.worldphoto.org/sony-world-photography-awards/student",
    category: "competitions",
  },
  {
    id: 38,
    title: "Red Dot Award: Design Concept",
    organization: "Red Dot Design Award",
    type: "Design Competition",
    eligibility: "Design, Industrial Design, Architecture & Fine Art Students",
    country: "Global",
    remote: "Yes",
    funding: "Award & Exhibition",
    link: "https://www.red-dot.org/design-concept",
    category: "competitions",
  },
  {
    id: 39,
    title: "Venice Biennale College Program",
    organization: "La Biennale di Venezia",
    type: "Arts & Media Workshop",
    eligibility: "Young Artists, Filmmakers, Dancers, Theatre & Writers",
    country: "Italy",
    remote: "No",
    funding: "Fully Funded",
    link: "https://www.labiennale.org/en/college",
    category: "bootcamps",
  },
  {
    id: 40,
    title: "Rotary Peace Fellowships",
    organization: "Rotary International",
    type: "Master's Fellowship",
    eligibility: "International Relations, Peace Studies, Development & Political Science",
    country: "Global",
    remote: "No",
    funding: "Fully Funded",
    link: "https://www.rotary.org/en/our-programs/peace-fellowships",
    category: "fellowships",
  },
  {
    id: 41,
    title: "Global Student Entrepreneur Award (GSEA)",
    organization: "Entrepreneurs' Organization",
    type: "Business Competition",
    eligibility: "Undergraduate Student Entrepreneurs & Startup Founders",
    country: "Global",
    remote: "Hybrid",
    funding: "Prize / Capital",
    link: "https://gsea.org/",
    category: "competitions",
  },
  {
    id: 42,
    title: "Hult Prize",
    organization: "Hult Prize Foundation",
    type: "Social Entrepreneurship",
    eligibility: "University Students across ALL fields",
    country: "Global",
    remote: "Hybrid",
    funding: "$1M Seed Funding",
    link: "https://www.hultprize.org/",
    category: "competitions",
  },
  {
    id: 43,
    title: "Echoing Green Fellowship",
    organization: "Echoing Green",
    type: "Social Innovation Fellowship",
    eligibility: "Emerging Social Innovators & Community Leaders",
    country: "Global",
    remote: "Yes",
    funding: "Stipend & Seed Funding",
    link: "https://echoinggreen.org/fellowship/",
    category: "fellowships",
  },
  {
    id: 44,
    title: "Varkey Foundation Global Student Prize",
    organization: "Varkey Foundation & Chegg.org",
    type: "Global Award",
    eligibility: "Students 16+ making exceptional real-world impact",
    country: "Global",
    remote: "Yes",
    funding: "$100,000 Award",
    link: "https://www.globalteacherprize.org/global-student-prize",
    category: "competitions",
  },
  {
    id: 45,
    title: "International Law Fellowship Programme",
    organization: "United Nations (UN Codification Division)",
    type: "Fellowship",
    eligibility: "Law Students & Young Legal Professionals",
    country: "Netherlands",
    remote: "No",
    funding: "Fully Funded",
    link: "https://legal.un.org/ilfp/",
    category: "fellowships",
  },
  {
    id: 46,
    title: "Young Climate Leaders Fellowship",
    organization: "United Nations Environment Programme (UNEP)",
    type: "Fellowship Program",
    eligibility: "Environmental Science, Climate & Sustainability Students",
    country: "Global",
    remote: "Hybrid",
    funding: "Fully Funded",
    link: "https://www.unep.org/youngchampions",
    category: "fellowships",
  },
  {
    id: 47,
    title: "Rhodes Scholarship",
    organization: "Rhodes Trust & University of Oxford",
    type: "Scholarship",
    eligibility: "Postgraduate Students & Outstanding Graduates",
    country: "United Kingdom",
    remote: "No",
    funding: "Fully Funded",
    link: "https://www.rhodeshouse.ox.ac.uk/scholarships/the-rhodes-scholarship/",
    category: "scholarships",
  },
  {
    id: 48,
    title: "Fulbright Foreign Student Program",
    organization: "U.S. Department of State",
    type: "Scholarship",
    eligibility: "Graduate Students, Young Professionals & Artists",
    country: "United States",
    remote: "No",
    funding: "Fully Funded",
    link: "https://fulbrightonline.org/",
    category: "scholarships",
  },
  {
    id: 49,
    title: "CERN Summer Student Programme",
    organization: "CERN",
    type: "Research Internship",
    eligibility: "Undergraduate & Master Students in Physics, CS, Engineering",
    country: "Switzerland",
    remote: "No",
    funding: "Paid Allowance & Travel",
    link: "https://careers.cern/summer",
    category: "internships",
  },
  {
    id: 50,
    title: "MLH Fellowship",
    organization: "Major League Hacking (MLH)",
    type: "Fellowship Program",
    eligibility: "Software Developers, CS Students & Open Source Enthusiasts",
    country: "Global",
    remote: "Yes",
    funding: "Stipend Available",
    link: "https://fellowship.mlh.io/",
    category: "fellowships",
  },
  {
    id: 51,
    title: "Schwarzman Scholars Program",
    organization: "Schwarzman College & Tsinghua University",
    type: "Master's Fellowship",
    eligibility: "Undergraduates & Young Professionals (Under 28)",
    country: "China",
    remote: "No",
    funding: "Fully Funded",
    link: "https://www.schwarzmanscholars.org/",
    category: "fellowships",
  },
  {
    id: 52,
    title: "Gates Cambridge Scholarship",
    organization: "Bill & Melinda Gates Foundation & University of Cambridge",
    type: "Scholarship",
    eligibility: "Postgraduate Applicants from outside the UK",
    country: "United Kingdom",
    remote: "No",
    funding: "Fully Funded",
    link: "https://www.gatescambridge.org/",
    category: "scholarships",
  },
  {
    id: 53,
    title: "L'Or\u00e9al Brandstorm",
    organization: "L'Or\u00e9al",
    type: "Business Competition",
    eligibility: "Undergraduate & Master's Students Worldwide",
    country: "Global",
    remote: "Hybrid",
    funding: "Intensive Intrapreneurship Mission & Awards",
    link: "https://brandstorm.loreal.com/",
    category: "competitions",
  },
  {
    id: 54,
    title: "Breakthrough Junior Challenge",
    organization: "Breakthrough Prize Foundation",
    type: "Science Competition",
    eligibility: "Students aged 13 to 18",
    country: "Global",
    remote: "Yes",
    funding: "$250,000 Scholarship",
    link: "https://breakthroughjuniorchallenge.org/",
    category: "competitions",
  },
  {
    id: 55,
    title: "DAAD Study Scholarships",
    organization: "DAAD (German Academic Exchange Service)",
    type: "Scholarship",
    eligibility: "Graduates & Postgraduates",
    country: "Germany",
    remote: "No",
    funding: "Fully Funded Monthly Stipend",
    link: "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
    category: "scholarships",
  },
  {
    id: 56,
    title: "Rise Challenge Program",
    organization: "Schmidt Futures & Rhodes Trust",
    type: "Fellowship Program",
    eligibility: "Youth aged 15 to 17",
    country: "Global",
    remote: "Hybrid",
    funding: "Higher Education Scholarships & Lifetime Network",
    link: "https://www.risefortheworld.org/",
    category: "fellowships",
  },
];

export function getOpportunitiesByCategory(category: OpportunityCategory): Opportunity[] {
  return OPPORTUNITIES.filter((o) => o.category === category);
}