import React from "react";
import { PALETTE } from "../TsFiles/Palette.ts";
import "../CssFiles/Background.css";

/* Flat polygon shapes (inspired by an SVGator "ambient background motion" reference) (inspired) */

type Shape = {
  id: string;
  top: string;
  left: string;
  width: number;
  height: number;
  color: string;
  opacity: number;
  clipPath?: string;
  borderRadius?: string;
  rotate: number;
  duration: number; // seconds
  delay: number; // seconds
  dx: number; // px, horizontal drift
  dy: number; // px, vertical drift
};

const SHAPES: Shape[] = [
  {
    id: "rect-mint",
    top: "-4%",
    left: "-6%",
    width: 320,
    height: 380,
    color: PALETTE.mint,
    opacity: 0.55,
    rotate: -6,
    duration: 16,
    delay: 0,
    dx: 26,
    dy: 20,
  },
  {
    id: "rect-lime",
    top: "2%",
    left: "34%",
    width: 340,
    height: 190,
    color: PALETTE.lime,
    opacity: 0.6,
    rotate: -4,
    duration: 14,
    delay: 0.6,
    dx: -30,
    dy: 24,
  },
  {
    id: "pentagon-peach-small",
    top: "8%",
    left: "36%",
    width: 110,
    height: 105,
    color: PALETTE.peach,
    opacity: 0.65,
    clipPath: "polygon(50% 0%, 100% 38%, 82% 100%, 18% 100%, 0% 38%)",
    rotate: 8,
    duration: 12,
    delay: 0.2,
    dx: 22,
    dy: -18,
  },
  {
    id: "triangle-coral-small",
    top: "6%",
    left: "70%",
    width: 60,
    height: 55,
    color: PALETTE.coral,
    opacity: 0.6,
    clipPath: "polygon(0% 0%, 100% 50%, 0% 100%)",
    rotate: 0,
    duration: 10,
    delay: 1,
    dx: -18,
    dy: 26,
  },
  {
    id: "pentagon-peach-large",
    top: "44%",
    left: "58%",
    width: 220,
    height: 210,
    color: PALETTE.peach,
    opacity: 0.5,
    clipPath: "polygon(50% 0%, 100% 38%, 82% 100%, 18% 100%, 0% 38%)",
    rotate: -3,
    duration: 18,
    delay: 0.4,
    dx: -28,
    dy: -22,
  },
  {
    id: "blob-mint-large",
    top: "30%",
    left: "62%",
    width: 420,
    height: 420,
    color: PALETTE.mint,
    opacity: 0.35,
    borderRadius: "42% 58% 60% 40% / 45% 40% 60% 55%",
    rotate: 0,
    duration: 20,
    delay: 0,
    dx: 34,
    dy: -30,
  },
  {
    id: "triangle-mint-bottom",
    top: "70%",
    left: "24%",
    width: 90,
    height: 90,
    color: PALETTE.mint,
    opacity: 0.55,
    clipPath: "polygon(50% 0%, 100% 100%, 0% 100%)",
    rotate: 0,
    duration: 13,
    delay: 0.8,
    dx: 20,
    dy: 24,
  },
  {
    id: "circle-coral",
    top: "72%",
    left: "10%",
    width: 64,
    height: 64,
    color: PALETTE.coral,
    opacity: 0.6,
    borderRadius: "50%",
    rotate: 0,
    duration: 11,
    delay: 0.3,
    dx: -24,
    dy: -20,
  },
  {
    id: "circle-lime-tiny",
    top: "78%",
    left: "50%",
    width: 22,
    height: 22,
    color: PALETTE.lime,
    opacity: 0.7,
    borderRadius: "50%",
    rotate: 0,
    duration: 9,
    delay: 1.2,
    dx: 16,
    dy: -18,
  },
  {
    id: "blob-lavender",
    top: "14%",
    left: "78%",
    width: 180,
    height: 170,
    color: "#C5B3D3",
    opacity: 0.5,
    borderRadius: "55% 45% 40% 60% / 50% 55% 45% 50%",
    rotate: 5,
    duration: 15,
    delay: 0.5,
    dx: -22,
    dy: 24,
  },
  {
    id: "pentagon-blush",
    top: "56%",
    left: "4%",
    width: 130,
    height: 124,
    color: "#F5CBCB",
    opacity: 0.6,
    clipPath: "polygon(50% 0%, 100% 38%, 82% 100%, 18% 100%, 0% 38%)",
    rotate: -10,
    duration: 13,
    delay: 0.9,
    dx: 18,
    dy: -22,
  },
  {
    id: "triangle-honeydew",
    top: "18%",
    left: "18%",
    width: 70,
    height: 66,
    color: "#EEF8CD",
    opacity: 0.65,
    clipPath: "polygon(50% 0%, 100% 100%, 0% 100%)",
    rotate: 12,
    duration: 11,
    delay: 0.2,
    dx: -20,
    dy: 18,
  },
  {
    id: "rect-pale-lime",
    top: "62%",
    left: "68%",
    width: 240,
    height: 140,
    color: "#F6FFDC",
    opacity: 0.5,
    rotate: 4,
    duration: 17,
    delay: 1.1,
    dx: 24,
    dy: -20,
  },
  {
    id: "circle-mint-pale",
    top: "38%",
    left: "6%",
    width: 48,
    height: 48,
    color: "#DAF9DE",
    opacity: 0.65,
    borderRadius: "50%",
    rotate: 0,
    duration: 10,
    delay: 0.4,
    dx: 16,
    dy: 22,
  },
  {
    id: "blob-skyblue",
    top: "84%",
    left: "80%",
    width: 200,
    height: 190,
    color: "#CFECF3",
    opacity: 0.45,
    borderRadius: "48% 52% 55% 45% / 40% 50% 50% 60%",
    rotate: -6,
    duration: 19,
    delay: 0.7,
    dx: -26,
    dy: -18,
  },
  {
    id: "triangle-pink-small",
    top: "48%",
    left: "88%",
    width: 54,
    height: 50,
    color: "#F9B2D7",
    opacity: 0.6,
    clipPath: "polygon(0% 0%, 100% 50%, 0% 100%)",
    rotate: -15,
    duration: 9,
    delay: 1.4,
    dx: -14,
    dy: 20,
  },
  {
    id: "pentagon-lavender-small",
    top: "92%",
    left: "40%",
    width: 90,
    height: 86,
    color: "#C5B3D3",
    opacity: 0.55,
    clipPath: "polygon(50% 0%, 100% 38%, 82% 100%, 18% 100%, 0% 38%)",
    rotate: 9,
    duration: 12,
    delay: 0.6,
    dx: 18,
    dy: -16,
  },
  {
    id: "circle-blush-tiny",
    top: "26%",
    left: "94%",
    width: 30,
    height: 30,
    color: "#F5CBCB",
    opacity: 0.65,
    borderRadius: "50%",
    rotate: 0,
    duration: 8,
    delay: 1.6,
    dx: -14,
    dy: 16,
  },
  {
    id: "blob-honeydew-small",
    top: "50%",
    left: "42%",
    width: 130,
    height: 120,
    color: "#EEF8CD",
    opacity: 0.4,
    borderRadius: "50% 50% 45% 55% / 55% 45% 55% 45%",
    rotate: -8,
    duration: 16,
    delay: 0.3,
    dx: 20,
    dy: 20,
  },
  {
    id: "triangle-pale-lime-tiny",
    top: "10%",
    left: "52%",
    width: 40,
    height: 38,
    color: "#F6FFDC",
    opacity: 0.6,
    clipPath: "polygon(50% 0%, 100% 100%, 0% 100%)",
    rotate: -18,
    duration: 10,
    delay: 1,
    dx: -16,
    dy: 14,
  },
  {
    id: "rect-mint-pale-small",
    top: "88%",
    left: "16%",
    width: 150,
    height: 90,
    color: "#DAF9DE",
    opacity: 0.5,
    rotate: 6,
    duration: 14,
    delay: 0.8,
    dx: 22,
    dy: -18,
  },
  {
    id: "circle-skyblue-small",
    top: "4%",
    left: "92%",
    width: 46,
    height: 46,
    color: "#CFECF3",
    opacity: 0.55,
    borderRadius: "50%",
    rotate: 0,
    duration: 12,
    delay: 1.3,
    dx: -18,
    dy: 20,
  },
];

/* added more shapes*/

const background: React.FC = () => (
  <div className="my-bg" aria-hidden="true">
    {SHAPES.map((s) => (
      <span
        key={s.id}
        className="my-shape"
        style={
          {
            top: s.top,
            left: s.left,
            width: `${s.width}px`,
            height: `${s.height}px`,
            background: s.color,
            opacity: s.opacity,
            clipPath: s.clipPath,
            borderRadius: s.borderRadius,
            "--rotate": `${s.rotate}deg`,
            "--dx": `${s.dx}px`,
            "--dy": `${s.dy}px`,
            animationDuration: `${s.duration}s`,
            animationDelay: `${s.delay}s`,
          } as React.CSSProperties
        }
      />
    ))}
  </div>
);

export default background;
